FROM bellsoft/liberica-openjre-debian:25-cds
WORKDIR /application
ARG JAR_FILE=target/*.jar
# Copy the jar file to the working directory and rename it to person.jar
COPY ${JAR_FILE} person.jar
# Execute the AOT cache training run
RUN java -XX:AOTCacheOutput=person.aot -Dspring.context.exit=onRefresh -Dspring.profiles.active=h2 -jar person.jar
# Start the application jar AOT Spring and AOT Cache
ENTRYPOINT ["java", "-XX:AOTCache=person.aot", "-Dspring.profiles.active=h2", "-jar", "person.jar"]